baseURL = 'https://hablandodeia.com/'
languageCode = 'es-MX'
title = 'Hablando De IA'

[params]
  description = 'Comunidad de entusiastas de la inteligencia artificial en Ciudad de MÃ©xico. Eventos, networking y recursos.'

[outputs]
  home = ['HTML', 'SITEMAP']
  page = ['HTML']

[markup.goldmark.renderer]
  unsafe = true
